// Code generated by protoc-gen-grpcq. DO NOT EDIT.
// versions:
// - protoc-gen-grpcq v0.1.0
// source: user.proto

package proto

import (
	context "context"
	grpcq "github.com/pbdeuchler/grpcq/go/grpcq"
)

// UserServiceConsumer is the server API for UserService service with grpcq.
// This interface is compatible with the gRPC UserServiceServer interface.
// Implementations should embed the gRPC Unimplemented server for compatibility.
type UserServiceConsumer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

// RegisterUserServiceConsumer registers the UserService consumer implementation
// with the provided queue adapter and configuration.
func RegisterUserServiceConsumer(adapter grpcq.QueueAdapter, srv UserServiceConsumer, opts ...grpcq.ServerOption) *grpcq.Server {
	// Create server with options - options are applied inside NewServer
	s := grpcq.NewServer(adapter, opts...)

	s.RegisterMethod("userservice.UserService", "CreateUser", func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.CreateUser(ctx, req.(*CreateUserRequest))
	}, func() interface{} { return &CreateUserRequest{} })
	s.RegisterMethod("userservice.UserService", "GetUser", func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.GetUser(ctx, req.(*GetUserRequest))
	}, func() interface{} { return &GetUserRequest{} })

	return s
}

// UserServiceProducer is the client API for UserService service with grpcq.
type UserServiceProducer interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpcq.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpcq.CallOption) (*GetUserResponse, error)
}

type userServiceProducer struct {
	cc *grpcq.Client
}

// NewUserServiceProducer creates a new UserService producer for grpcq.
func NewUserServiceProducer(adapter grpcq.QueueAdapter, opts ...grpcq.ClientOption) UserServiceProducer {
	return &userServiceProducer{
		cc: grpcq.NewClient(adapter, opts...),
	}
}

func (c *userServiceProducer) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpcq.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "userservice.UserService", "CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceProducer) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpcq.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "userservice.UserService", "GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
