// Code generated by protoc-gen-grpcq. DO NOT EDIT.
// versions:
// - protoc-gen-grpcq v0.1.0
// source: user.proto

package proto

import (
	context "context"
	grpcq "github.com/pbdeuchler/grpcq/go/grpcq"
)

// UserServiceQServer is the server API for UserService service with grpcq.
// This interface is compatible with the gRPC UserServiceServer interface.
// Implementations should embed the gRPC Unimplemented server for compatibility.
type UserServiceQServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

// RegisterUserServiceQServer registers the UserService server implementation
// with the provided queue adapter and configuration.
func RegisterUserServiceQServer(adapter grpcq.QueueAdapter, srv UserServiceQServer, opts ...grpcq.ServerOption) *grpcq.Server {
	cfg := &grpcq.ServerConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	s := grpcq.NewServer(adapter, opts...)

	s.RegisterMethod("userservice.UserService", "CreateUser", func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.CreateUser(ctx, req.(*CreateUserRequest))
	}, func() interface{} { return &CreateUserRequest{} })
	s.RegisterMethod("userservice.UserService", "GetUser", func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.GetUser(ctx, req.(*GetUserRequest))
	}, func() interface{} { return &GetUserRequest{} })

	return s
}

// UserServiceQClient is the client API for UserService service with grpcq.
type UserServiceQClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpcq.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpcq.CallOption) (*GetUserResponse, error)
}

type userServiceQClient struct {
	cc *grpcq.Client
}

// NewUserServiceQClient creates a new UserService client for grpcq.
func NewUserServiceQClient(adapter grpcq.QueueAdapter, opts ...grpcq.ClientOption) UserServiceQClient {
	return &userServiceQClient{
		cc: grpcq.NewClient(adapter, opts...),
	}
}

func (c *userServiceQClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpcq.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "userservice.UserService", "CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceQClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpcq.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "userservice.UserService", "GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

